### ISSUE TITLE
Suggestion: Saver

### ISSUE THREAD

**Issue by Marco15453** [RyanLandDev/DFSchematics#1]
Make a Function for Saving

**Comment by ryandev2** [comment]
> Make a Function for Saving

Are you talking about the ability to select a region in-game and convert that to a data function?

**Comment by Marco15453** [comment]
yes

**Comment by Marco15453** [comment]
and maybe make it so it can be converted into an .schem or something if possible

**Comment by ryandev2** [comment]
I thought about this earlier. That would require a Minecraft mod which I feel like is out of scope for this project, but I am not 100% sure yet.

However, you can achieve pretty much the same thing using the Litematica mod, you can save regions to .litematic files within Minecraft and then import them through DFSchematics. (Litematic files will be supported soon.)

**Comment by ryandev2** [comment]
I will add a DF template which allows you to save schematics within a plot (for personal player worlds, eg skyblock)

**Comment by ryandev2** [comment]
> I will add a DF template which allows you to save schematics within a plot (for personal player worlds, eg skyblock)

@Marco15453 is this what you're looking for?

**Comment by Marco15453** [comment]
I mean like, that you can Save something and then export it as .schem file

**Comment by ryandev2** [comment]
> I thought about this earlier. That would require a Minecraft mod which I feel like is out of scope for this project, but I am not 100% sure yet.
> 
> However, you can achieve pretty much the same thing using the Litematica mod, you can save regions to .litematic files within Minecraft and then import them through DFSchematics. (Litematic files will be supported soon.)

See this comment

**Comment by Marco15453** [comment]
> I will add a DF template which allows you to save schematics within a plot (for personal player worlds, eg skyblock)
But this is also a nice thing to have

**Comment by ryandev2** [comment]
Late conclusion:
This is out of scope for this project; consult a mod like Litematica or WorldEdit to save schematic files.
