### ISSUE TITLE
Not recognizing CodeClient

### ISSUE THREAD

**Issue by cataclysmguy** [RyanLandDev/DFSchematics#11]
Literally just doesn't connect to codeclient.
CodeClient is installing perfectly.
DFSchematics mod is installed.
Using DFSchematics.exe file.

**Comment by ryandev2** [comment]
Could you ensure the API is enabled in CodeClient's config?
And try using the Retry button

**Comment by Loxding** [comment]
Same issue, it says it doesn't have authorization to connect, API is on for CodeClient and retry-ed it several times

**Comment by ryandev2** [comment]
Hm this issue does not occur on my machine. Could you run the program using the command line to see what error it gives if any? this is how:

- download the .jar file
- open cmd
- run `java -jar filelocation.jar`

**Comment by Loxding** [comment]
Got it to work thx

**Comment by ryandev2** [comment]
How did you fix it?

**Comment by Loxding** [comment]
Reinstalled java
