### ISSUE TITLE
Suggestion: Modrinth

### ISSUE THREAD

**Issue by Marco15453** [RyanLandDev/DFSchematics#3]
Upload the Mod to [modrinth.com](https://modrinth.com)

**Comment by ryandev2** [comment]
Technically this is not a mod but a desktop application, and Modrinth does not support applications. I looked and only found the following types of supported content: 
![image](https://github.com/RyanLandDev/DFSchematics/assets/46247385/48f41b74-4093-4942-b7d6-846532e9e1be)

**Comment by Marco15453** [comment]
alright
