### ISSUE TITLE
Bug: .schematic files doesn't load

### ISSUE THREAD

**Issue by Marco15453** [RyanLandDev/DFSchematics#4]
for some .schematic files it stays on "Reading" [Screenshot](https://s.4eo.xyz/Marco/4d625df8-18b4-4a15-852a-93241d8fdc3b-602-432-23-12-2023.png) and for some it goes trough but when placing the function it looks like [this](https://s.4eo.xyz/Marco/558a41bb-9dba-4496-978a-aa699c07f369-633-541-23-12-2023.png) (Blocks Variable)

**Comment by ryandev2** [comment]
Thank you for your report!

Could you send me the .schematic file you used?

I'm guessing you tried importing an unsupported format. There are multiple legacy formats using the `.schematic` extension (e.g. MCEdit), at the moment DFSchematics only supports Schematica with this extension. However, the parser could also be the problem. I'll need the file to make sure.

The blocks variable in the screenshot you sent only contains air blocks.

**Comment by Marco15453** [comment]
[Schematics I tried.zip](https://github.com/RyanLandDev/DFSchematics/files/13759210/Those.i.tried.zip)
Those are the .schematic file i tried

**Comment by Marco15453** [comment]
some worked but was extremly bugged and some didn't even load

**Comment by ryandev2** [comment]
I have investigated this issue a bit more.

See related issue: https://github.com/SandroHc/schematic4j/issues/5

For now, you can convert your schematics to .schem files using WorldEdit and import those until the issue is fixed.

**Comment by Marco15453** [comment]
I have tried that, but it doesn't seems to work

**Comment by ryandev2** [comment]
> I have tried that, but it doesn't seems to work

What did you try exactly? You could import the schematics into your singleplayer world using Litematica or something and save it using WorldEdit into .schem format

**Comment by ryandev2** [comment]
For litematics you can use this program: https://github.com/GoldenDelicios/Lite2Edit
