### ISSUE TITLE
Bug: Player heads spawn with their texture in the wrong spot

### ISSUE THREAD

**Issue by Brxzillian** [RyanLandDev/DFSchematics#6]
Schematic File Type: .litematic

Theres a weird issue where always one player head from maps i paste is placed as a textureless head (steve head) in their proper location and their textured version is pasted outside of the map ( The textured version always pastes at the border of the plot in the negative X direction? )

Expected Texture Location:
[2024-01-07_13 14 56](https://github.com/RyanLandDev/DFSchematics/assets/155843802/87d88377-0621-41ee-bcf6-85d834236f5a)

Actual Texture Location
[2024-01-07_13 15 11](https://github.com/RyanLandDev/DFSchematics/assets/155843802/c53e2143-e236-45e1-a773-ddf3e58e8aaf)

**Comment by ryandev2** [comment]
Could you send me the .litematic file you used? And is everything else in the schematic okay?

**Comment by Brxzillian** [comment]
> Could you send me the .litematic file you used? And is everything else in the schematic okay?

The schematic works mostly fine however: 

Certain blocks always paste waterlogged=true despite being saved as waterlogged=false (Sea Pickles and Coral Blocks used to be there but i had to remove because of that) 

Sign text is not being set (The map has 2 spruce signs with text but they always paste without it. I noticed in the code it only had Oak Signs being checked and tried to put all sign types but that didnt fix)

And the issue itself, a seemingly random player head has no texture

https://www.mediafire.com/file/qwr8e65yu8r541l/Highrise.litematic/file

**Comment by ryandev2** [comment]
Fixed, thank you for the report :)
