### ISSUE TITLE
Not being able to launch the .exe

### ISSUE THREAD

**Issue by CoderEliasDF** [RyanLandDev/DFSchematics#7]
Everytime I launch the DFSchematic.exe file I get this message:
<img width="264" alt="image" src="https://github.com/RyanLandDev/DFSchematics/assets/156214450/4e2c9254-c84e-48fd-95dc-84e5014bc612">
Idk how to fix this so I am therefore asking for help.

**Comment by ryandev2** [comment]
Like the error message suggests you need to have JRE 17 installed on your machine.

You have to download Java 17 which can be found here: https://www.java.com/en/download
