### ISSUE TITLE
Schematic Menu Crashing

### ISSUE THREAD

**Issue by CoderEliasDF** [RyanLandDev/DFSchematics#8]
Every time I put in a specific schematic file the DFschem.exe crashes.
This is the schematic I used:
https://www.planetminecraft.com/project/kingdoms-spawn-6105677/

**Comment by ryandev2** [comment]
This is a very large schematic (in fact it doesn't even come close to fitting on a massive plot), which requires the program to make a lot of calculations.

_It is 722x327x898 blocks which comes down to 212,012,412 iterations._
![image](https://github.com/RyanLandDev/DFSchematics/assets/46247385/35f55cab-6da7-424b-b0ba-080c13611992)

I tried loading the schematic myself, in my case the program froze for a few seconds and then imported the file successfully. If you still want to use this schematic, I suggest you simply import the schematic again and give it a minute to process (don't close it). The amount of time it takes varies per machine, but shouldn't take long.
![image](https://github.com/RyanLandDev/DFSchematics/assets/46247385/de5e05f6-480a-40d4-8252-f2d4930d0ad3)

To use it on a plot despite its massive size, you could load the entire schematic into a singleplayer world and create a new schematic file that does fit on a plot.
